version: "3.9"

services:
  web:
    build: app/
    image: ksgi/geocoder-platform-web:latest
    volumes:
      - ./app:/code/app
    ports:
      - "7001:8000"
    depends_on:
      - "db"
    container_name: point-web

  db:
    image: ksgi/geocoder-platform-db:latest
    volumes:
      - gisdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=census
      - POSTGRES_PASSWORD=census
    shm_size: 1gb
    container_name: point-db

  worker:
    image: ksgi/geocoder-platform-web:latest
    entrypoint: celery -A worker.celery worker --loglevel=info -c 10
    volumes:
      - ./app:/code/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
    container_name: point-worker

  redis:
    image: redis:7
    container_name: point-redis

volumes:
  gisdata:
